### ISSUE TITLE
[TASK] Create a diagram accurately representing the game rules

### ISSUE THREAD

**Issue by Luke-Sheltraw** [cse112-sp24-group12/cse112-sp24-group12#2]
**What needs to be done?**
We had a bunch of ideas floating around about the rules. We need to narrow our cone of uncertainty, and decide conclusively what the game rules are.

**What should be delivered?**
Ideally, a state machine or something similar representing a _complete_ first iteration of the game rules. It should handle any edge cases you can imagine. Upload as a PDF to a new folder: `/design/prototypes`.

**Additional info**
Since this is something that affects the general direction of the project, let's make sure to keep everyone in the loop.

**Comment by harshilxd** [comment]
Added the logic of the game, and multipliers in the pdf. Defined which suite wins, and which loses. Defined the logic of penticons being neutrals.
